import { defineConfig } from 'astro/config';

// Staging build for btf.net on Cloudflare Pages (project temp-btf).
// The Framer-derived pages and assets live in site/ (generated by scripts/build_site.py
// from the local-only source-framer/ export). Astro serves that folder as its static
// files, unchanged, and adds the real 404 page from src/pages/404.astro.
export default defineConfig({
  publicDir: 'site',
  outDir: 'dist',
  devToolbar: { enabled: false },
});
